# Use `make up`, not `docker compose up`,
# as this YAML requires ${...} variables to be set.
---
services:
  node:
    build: .
    hostname: ${NODE_NAME}
    privileged: true
    restart: always
    networks:
      default:
        ipv4_address: ${NODE_IP}
    ports:
      # <host>:<container>
      # etcd (default: 2379)
      - ${PORT_ETCD}:${PORT_ETCD}
      # kube-apiserver (default: 6443)
      - ${PORT_KUBE_APISERVER}:${PORT_KUBE_APISERVER}
      # kubelet (default: 10250)
      - ${PORT_KUBELET}:${PORT_KUBELET}
      # flannel vxlan (default: 8472)
      - ${PORT_FLANNEL}:${PORT_FLANNEL}/udp
      # calico vxlan (default: 4789)
      - ${PORT_CALICO}:${PORT_CALICO}/udp
      # calico typha (default: 5473). Only the host port is configurable;
      # the container port is fixed to 5473, as the calico-node pods on the
      # other hosts connect to the port number found in the endpoints of the
      # calico-typha service.
      - ${PORT_CALICO_TYPHA}:5473
    volumes:
      - .:/usernetes:ro
      - /boot:/boot:ro
      - /lib/modules:/lib/modules:ro
      - node-var:/var
      - node-opt:/opt
      - node-etc:/etc
      - type: tmpfs
        target: /run
      - type: tmpfs
        target: /tmp
    working_dir: /usernetes
    environment:
      KUBECONFIG: /etc/kubernetes/admin.conf
      HOST_IP: ${HOST_IP}
      NODE_IP: ${NODE_IP}
      POD_SUBNET: ${POD_SUBNET}
      SERVICE_SUBNET: ${SERVICE_SUBNET}
      # CNI driver ("flannel" or "calico").
      # Set to "calico" to enable the Calico-specific hacks of the entrypoint.
      CNI: ${CNI:-flannel}
      # Set to 1 to disable the IP checksum offloading on flannel.1.
      # Needed when the network is provided by slirp4netns.
      FLANNEL_IGNORE_IP_CHECKSUM: ${FLANNEL_IGNORE_IP_CHECKSUM:-}
      PORT_CALICO: ${PORT_CALICO}
    sysctls:
      - net.ipv4.ip_forward=1
      # In addition, `net.ipv4.conf.default.rp_filter`
      # has to be set to 0 (disabled) or 2 (loose)
      # in the daemon's network namespace.
    annotations:
      # Accelerate network for nerdctl >= 2.0.0-beta.4 with bypass4netns >= 0.4.1
      "nerdctl/bypass4netns": "${BYPASS4NETNS:-false}"
      "nerdctl/bypass4netns-ignore-bind": "true"
      "nerdctl/bypass4netns-ignore-subnets": "${BYPASS4NETNS_IGNORE_SUBNETS:-}"
networks:
  default:
    ipam:
      config:
        # Each of the nodes has to have a different IP.
        # The node IP here is not accessible from other nodes.
        - subnet: ${NODE_SUBNET}
volumes:
  node-var: {}
  node-opt: {}
  node-etc: {}
